In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassiifier
music_data = pd.read_csv(r"C:\Users\user\PycharmProjects\practice\music.csv")
music_data

    age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [4]:
X = music_data.drop(columns=['genre'])
X

    age  gender
0    20       1
1    23       1
2    25       1
3    26       1
4    29       1
5    30       1
6    31       1
7    33       1
8    37       1
9    20       0
10   21       0
11   25       0
12   26       0
13   27       0
14   30       0
15   31       0
16   34       0
17   35       0

In [5]:
y = music_data['genre']
y

0        HipHop
1        HipHop
2        HipHop
3          Jazz
4          Jazz
5          Jazz
6     Classical
7     Classical
8     Classical
9         Dance
10        Dance
11        Dance
12     Acoustic
13     Acoustic
14     Acoustic
15    Classical
16    Classical
17    Classical
Name: genre, dtype: object

In [5]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

music_data = pd.read_csv(r"C:\Users\user\PycharmProjects\practice\music.csv")
X = music_data.drop(columns=['genre'])
y = music_data['genre']

#now we need to create a new instance of the class 'DecisionTreeClassiifier'.
#so we created an object 'model' and set it to a new instance of 'DecisionTreeClassiifier'
model = DecisionTreeClassifier()   #here a model is created
model.fit(X.values, y.values)   #this method takes the input (X) and output (y) data sets 
predictions = model.predict([ [21, 1], [22, 0] ])   #this method takes a 2D array: an outer array and an inner array
                           #here we pass 2 new input sets, so we ask the model to make 2 predictions at the same time
predictions    #here we inspect our code

array(['HipHop', 'Dance'], dtype=object)

In [18]:
# Calculating the accuracy of a model
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

music_data = pd.read_csv(r"C:\Users\user\PycharmProjects\practice\music.csv")
X = music_data.drop(columns=['genre'])
y = music_data['genre']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)  # 0.2 means 20% for testing (80% for training)

model = DecisionTreeClassifier()  
model.fit(X_train, y_train)  
predictions = model.predict(X_test)  

score = accuracy_score(y_test, predictions)
score
#knack: we can repeatedly run these codes by pressing Ctrl + Enter

1.0

In [1]:
# Persisting models by storing the model that's been trained 
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
import joblib   #this 'joblib' object has methods for saving and loading models

music_data = pd.read_csv(r"C:\Users\user\PycharmProjects\practice\music.csv")
X = music_data.drop(columns=['genre'])
y = music_data['genre']

model = DecisionTreeClassifier() 
model.fit(X.values, y.values) 

joblib.dump(model, 'music-recommender.joblib')   #here we give '.dump' 2 args, among which the arg 'music-recommender.joblib' is the file for storing the trained model

['music-recommender.joblib']

In [2]:
# Loading the trained model 
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
import joblib  

model = joblib.load('music-recommender.joblib')
predictions = model.predict([ [21, 1], [22, 0] ]) 
predictions

array(['HipHop', 'Dance'], dtype=object)

In [4]:
# Visualizing a Decision Tree (exporting our model in a visual format)
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree   #this 'tree' object has a method for exporting our Decision Tree in a graphical format

music_data = pd.read_csv(r"C:\Users\user\PycharmProjects\practice\music.csv")
X = music_data.drop(columns=['genre'])
y = music_data['genre']

model = DecisionTreeClassifier() 
model.fit(X.values, y.values) 

#after we train our model, let's call 
tree.export_graphviz(model, out_file='music-recommender.dot',   #the 2nd arg is name of an output file. Here we use keyword args 'coz this method takes so many parameters, and we wanna seletively pass keyword args without worrying about their order
                                                #here '.dot' is a textual graph-description language
                     feature_names=['age','gender'],   #the 3rd arg is the properties/features of our data. And we can see the rules in the Decision Tree nodes 
                     class_names=sorted(y.unique()),   #the 4th arg is set to be the list of classes/labels in our output data set. Here 'y.unique()' returns the unique list of classes, and we call the 'sorted' function to sort it alphabetically
                     label='all', 
                     rounded=True, 
                     filled=True)   #here we pass 7 args